#!/usr/bin/bash
sdk_path="/home/ali/extra/libs/java/javafx-sdk-23/lib"
jarfile="app.jar"
com_folder="src"
newest=$(find "$com_folder" -type f -print0 | xargs -0 ls -t | head -n 1)
compl(){
    javac -d outDir --module-path "$sdk_path" -cp "$sdk_path/javafx.controls.jar:$sdk_path/javafx.graphics.jar:$sdk_path/javafx.base.jar:$sdk_path/javafx.fxml.jar"  src/*.java
}
makeJar(){
    cp -r src/resources/* outDir/ && jar --create --file "$jarfile" --main-class Main -C outDir . && rm -rf outDir
}

if [ "$jarfile" -nt "$newest" ]; then
    clear && echo "running..." && javaGui "$jarfile"
else
    clear && echo "compiling..." && compl && makeJar && javaGui "$jarfile"
fi