#!/usr/bin/bash
main="/home/ali/extra/study/gui/java/src/main/java/com/example/java/Main.java"
jarfile="/home/ali/extra/study/gui/java/MyApp.jar"
compl(){
    javac -d outDir --module-path "/home/ali/.m2/repository/org/openjfx/javafx-controls/17.0.6/javafx-controls-17.0.6-linux.jar:/home/ali/.m2/repository/org/openjfx/javafx-graphics/17.0.6/javafx-graphics-17.0.6-linux.jar:/home/ali/.m2/repository/org/openjfx/javafx-base/17.0.6/javafx-base-17.0.6-linux.jar:/home/ali/.m2/repository/org/openjfx/javafx-fxml/17.0.6/javafx-fxml-17.0.6-linux.jar" -cp "/home/ali/.m2/repository/org/openjfx/javafx-controls/17.0.6/javafx-controls-17.0.6.jar:/home/ali/.m2/repository/org/openjfx/javafx-graphics/17.0.6/javafx-graphics-17.0.6.jar:/home/ali/.m2/repository/org/openjfx/javafx-base/17.0.6/javafx-base-17.0.6.jar:/home/ali/.m2/repository/org/openjfx/javafx-fxml/17.0.6/javafx-fxml-17.0.6.jar" src/main/java/module-info.java src/main/java/com/example/java/Main.java
}
makeJar(){
    cp -r src/main/resources/* outDir/ && jar --create --file MyApp.jar --main-class com.example.java.Main -C outDir . && rm -rf outDir
}
runJar(){
    java --module-path "/home/ali/.m2/repository/org/openjfx/javafx-controls/17.0.6/javafx-controls-17.0.6-linux.jar:/home/ali/.m2/repository/org/openjfx/javafx-graphics/17.0.6/javafx-graphics-17.0.6-linux.jar:/home/ali/.m2/repository/org/openjfx/javafx-base/17.0.6/javafx-base-17.0.6-linux.jar:/home/ali/.m2/repository/org/openjfx/javafx-fxml/17.0.6/javafx-fxml-17.0.6-linux.jar:/home/ali/.m2/repository/org/openjfx/javafx-web/17.0.6/javafx-web-17.0.6-linux.jar:/home/ali/.m2/repository/org/openjfx/javafx-swing/17.0.6/javafx-swing-17.0.6-linux.jar:/home/ali/.m2/repository/org/openjfx/javafx-media/17.0.6/javafx-media-17.0.6-linux.jar" --add-modules javafx.controls,javafx.fxml -jar MyApp.jar
}

if [ "$jarfile" -nt "$main" ]; then
   clear && echo "running..." && runJar 
else
   clear && echo "compiling..." && compl && makeJar && runJar 
fi  