#!/usr/bin/bash
jarfile="app.jar"
sdk_path="/home/ali/extra/libs/java/javafx-sdk-23/lib"
com_folder="src"
compl(){
    javac -d outDir --module-path "$sdk_path" -cp "$sdk_path/javafx.controls.jar:$sdk_path/javafx.graphics.jar:$sdk_path/javafx.base.jar:$sdk_path/javafx.fxml.jar" src/main/java/module-info.java src/main/java/com/example/java/*.java
}
makeJar(){
    cp -r src/main/resources/* outDir/ && jar --create --file "$jarfile" --main-class com.example.java.Main -C outDir . && rm -rf outDir
}
newest=$(find "$com_folder" -type f -print0 | xargs -0 ls -t | head -n 1)

if [ "$jarfile" -nt "$newest" ]; then
    clear && echo "running..." && javaGui "$jarfile"
else
    clear && echo "compiling..." && compl && makeJar &&  javaGui "$jarfile"
fi